"""Initial Adler schema

Revision ID: 05e2adf69ea6
Revises:
Create Date: 2026-06-02 15:40:22.029970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e2adf69ea6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_appointment_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('appointment_id', sa.String(length=120), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_appointment_confirmations_appointment_id'), 'adler_appointment_confirmations', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_adler_appointment_confirmations_id'), 'adler_appointment_confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_adler_appointment_confirmations_patient_id'), 'adler_appointment_confirmations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_appointment_confirmations_source_message_id'), 'adler_appointment_confirmations', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_adler_appointment_confirmations_status'), 'adler_appointment_confirmations', ['status'], unique=False)
    op.create_index(op.f('ix_adler_appointment_confirmations_tenant_id'), 'adler_appointment_confirmations', ['tenant_id'], unique=False)
    op.create_table('adler_appointments',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=40), nullable=False),
    sa.Column('session_label', sa.String(length=160), nullable=False),
    sa.Column('mode', sa.String(length=80), nullable=False),
    sa.Column('room_label', sa.String(length=120), nullable=False),
    sa.Column('prep_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_adler_appointment_tenant_id')
    )
    op.create_index(op.f('ix_adler_appointments_id'), 'adler_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_adler_appointments_patient_id'), 'adler_appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_appointments_pk'), 'adler_appointments', ['pk'], unique=False)
    op.create_index(op.f('ix_adler_appointments_status'), 'adler_appointments', ['status'], unique=False)
    op.create_index(op.f('ix_adler_appointments_tenant_id'), 'adler_appointments', ['tenant_id'], unique=False)
    op.create_table('adler_clinical_analysis_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('approach', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'patient_id', 'session_number', 'approach', 'version', name='uq_adler_analysis_version')
    )
    op.create_index(op.f('ix_adler_clinical_analysis_json_approach'), 'adler_clinical_analysis_json', ['approach'], unique=False)
    op.create_index(op.f('ix_adler_clinical_analysis_json_id'), 'adler_clinical_analysis_json', ['id'], unique=False)
    op.create_index(op.f('ix_adler_clinical_analysis_json_patient_id'), 'adler_clinical_analysis_json', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_clinical_analysis_json_session_id'), 'adler_clinical_analysis_json', ['session_id'], unique=False)
    op.create_index(op.f('ix_adler_clinical_analysis_json_session_number'), 'adler_clinical_analysis_json', ['session_number'], unique=False)
    op.create_index(op.f('ix_adler_clinical_analysis_json_tenant_id'), 'adler_clinical_analysis_json', ['tenant_id'], unique=False)
    op.create_table('adler_clinical_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('approach', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symptoms_json', sa.JSON(), nullable=False),
    sa.Column('emotions_json', sa.JSON(), nullable=False),
    sa.Column('events_json', sa.JSON(), nullable=False),
    sa.Column('behaviors_json', sa.JSON(), nullable=False),
    sa.Column('medication_json', sa.JSON(), nullable=False),
    sa.Column('time_context', sa.String(length=240), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_clinical_sessions_approach'), 'adler_clinical_sessions', ['approach'], unique=False)
    op.create_index(op.f('ix_adler_clinical_sessions_id'), 'adler_clinical_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_adler_clinical_sessions_patient_id'), 'adler_clinical_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_clinical_sessions_session_number'), 'adler_clinical_sessions', ['session_number'], unique=False)
    op.create_index(op.f('ix_adler_clinical_sessions_tenant_id'), 'adler_clinical_sessions', ['tenant_id'], unique=False)
    op.create_table('adler_engagement_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('flag_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_engagement_flags_flag_type'), 'adler_engagement_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_adler_engagement_flags_id'), 'adler_engagement_flags', ['id'], unique=False)
    op.create_index(op.f('ix_adler_engagement_flags_patient_id'), 'adler_engagement_flags', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_engagement_flags_severity'), 'adler_engagement_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_adler_engagement_flags_tenant_id'), 'adler_engagement_flags', ['tenant_id'], unique=False)
    op.create_table('adler_evolution_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('from_session', sa.Integer(), nullable=True),
    sa.Column('to_session', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_evolution_snapshots_id'), 'adler_evolution_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_adler_evolution_snapshots_patient_id'), 'adler_evolution_snapshots', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_evolution_snapshots_tenant_id'), 'adler_evolution_snapshots', ['tenant_id'], unique=False)
    op.create_table('adler_generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('draft_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_generated_documents_document_type'), 'adler_generated_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_adler_generated_documents_id'), 'adler_generated_documents', ['id'], unique=False)
    op.create_index(op.f('ix_adler_generated_documents_patient_id'), 'adler_generated_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_generated_documents_session_id'), 'adler_generated_documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_adler_generated_documents_tenant_id'), 'adler_generated_documents', ['tenant_id'], unique=False)
    op.create_table('adler_patients',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('initials', sa.String(length=20), nullable=False),
    sa.Column('focus', sa.String(length=240), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('current_protocol', sa.Text(), nullable=False),
    sa.Column('default_session', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_adler_patient_tenant_id')
    )
    op.create_index(op.f('ix_adler_patients_id'), 'adler_patients', ['id'], unique=False)
    op.create_index(op.f('ix_adler_patients_name'), 'adler_patients', ['name'], unique=False)
    op.create_index(op.f('ix_adler_patients_pk'), 'adler_patients', ['pk'], unique=False)
    op.create_index(op.f('ix_adler_patients_status'), 'adler_patients', ['status'], unique=False)
    op.create_index(op.f('ix_adler_patients_tenant_id'), 'adler_patients', ['tenant_id'], unique=False)
    op.create_table('adler_pharmacogenetics_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('gene', sa.String(length=80), nullable=False),
    sa.Column('phenotype', sa.String(length=160), nullable=False),
    sa.Column('source_lab', sa.String(length=180), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_pharmacogenetics_results_gene'), 'adler_pharmacogenetics_results', ['gene'], unique=False)
    op.create_index(op.f('ix_adler_pharmacogenetics_results_id'), 'adler_pharmacogenetics_results', ['id'], unique=False)
    op.create_index(op.f('ix_adler_pharmacogenetics_results_patient_id'), 'adler_pharmacogenetics_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_pharmacogenetics_results_tenant_id'), 'adler_pharmacogenetics_results', ['tenant_id'], unique=False)
    op.create_table('adler_risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_risk_scores_id'), 'adler_risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_adler_risk_scores_patient_id'), 'adler_risk_scores', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_risk_scores_risk_type'), 'adler_risk_scores', ['risk_type'], unique=False)
    op.create_index(op.f('ix_adler_risk_scores_session_id'), 'adler_risk_scores', ['session_id'], unique=False)
    op.create_index(op.f('ix_adler_risk_scores_session_number'), 'adler_risk_scores', ['session_number'], unique=False)
    op.create_index(op.f('ix_adler_risk_scores_tenant_id'), 'adler_risk_scores', ['tenant_id'], unique=False)
    op.create_table('adler_tenant_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=True),
    sa.Column('patient_name', sa.String(length=180), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_tenant_documents_id'), 'adler_tenant_documents', ['id'], unique=False)
    op.create_index(op.f('ix_adler_tenant_documents_patient_id'), 'adler_tenant_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_tenant_documents_tenant_id'), 'adler_tenant_documents', ['tenant_id'], unique=False)
    op.create_table('adler_tenant_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_tenant_notes_id'), 'adler_tenant_notes', ['id'], unique=False)
    op.create_index(op.f('ix_adler_tenant_notes_tenant_id'), 'adler_tenant_notes', ['tenant_id'], unique=True)
    op.create_table('adler_whatsapp_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('adherence', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consent_status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_whatsapp_checkins_id'), 'adler_whatsapp_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_checkins_patient_id'), 'adler_whatsapp_checkins', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_checkins_tenant_id'), 'adler_whatsapp_checkins', ['tenant_id'], unique=False)
    op.create_table('adler_whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=True),
    sa.Column('external_message_id', sa.String(length=180), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('phone_hash', sa.String(length=180), nullable=True),
    sa.Column('intent', sa.String(length=80), nullable=True),
    sa.Column('template_key', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('safety_classification', sa.String(length=80), nullable=False),
    sa.Column('clinical_boundary_notice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_whatsapp_messages_direction'), 'adler_whatsapp_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_external_message_id'), 'adler_whatsapp_messages', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_id'), 'adler_whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_intent'), 'adler_whatsapp_messages', ['intent'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_patient_id'), 'adler_whatsapp_messages', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_phone_hash'), 'adler_whatsapp_messages', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_adler_whatsapp_messages_tenant_id'), 'adler_whatsapp_messages', ['tenant_id'], unique=False)
    op.create_table('crm_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_users_email'), 'crm_users', ['email'], unique=True)
    op.create_index(op.f('ix_crm_users_id'), 'crm_users', ['id'], unique=False)
    op.create_table('crm_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['crm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_user_sessions_expires_at'), 'crm_user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_crm_user_sessions_id'), 'crm_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_crm_user_sessions_token_hash'), 'crm_user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_crm_user_sessions_user_id'), 'crm_user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_user_sessions_user_id'), table_name='crm_user_sessions')
    op.drop_index(op.f('ix_crm_user_sessions_token_hash'), table_name='crm_user_sessions')
    op.drop_index(op.f('ix_crm_user_sessions_id'), table_name='crm_user_sessions')
    op.drop_index(op.f('ix_crm_user_sessions_expires_at'), table_name='crm_user_sessions')
    op.drop_table('crm_user_sessions')
    op.drop_index(op.f('ix_crm_users_id'), table_name='crm_users')
    op.drop_index(op.f('ix_crm_users_email'), table_name='crm_users')
    op.drop_table('crm_users')
    op.drop_index(op.f('ix_adler_whatsapp_messages_tenant_id'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_phone_hash'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_patient_id'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_intent'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_id'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_external_message_id'), table_name='adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_messages_direction'), table_name='adler_whatsapp_messages')
    op.drop_table('adler_whatsapp_messages')
    op.drop_index(op.f('ix_adler_whatsapp_checkins_tenant_id'), table_name='adler_whatsapp_checkins')
    op.drop_index(op.f('ix_adler_whatsapp_checkins_patient_id'), table_name='adler_whatsapp_checkins')
    op.drop_index(op.f('ix_adler_whatsapp_checkins_id'), table_name='adler_whatsapp_checkins')
    op.drop_table('adler_whatsapp_checkins')
    op.drop_index(op.f('ix_adler_tenant_notes_tenant_id'), table_name='adler_tenant_notes')
    op.drop_index(op.f('ix_adler_tenant_notes_id'), table_name='adler_tenant_notes')
    op.drop_table('adler_tenant_notes')
    op.drop_index(op.f('ix_adler_tenant_documents_tenant_id'), table_name='adler_tenant_documents')
    op.drop_index(op.f('ix_adler_tenant_documents_patient_id'), table_name='adler_tenant_documents')
    op.drop_index(op.f('ix_adler_tenant_documents_id'), table_name='adler_tenant_documents')
    op.drop_table('adler_tenant_documents')
    op.drop_index(op.f('ix_adler_risk_scores_tenant_id'), table_name='adler_risk_scores')
    op.drop_index(op.f('ix_adler_risk_scores_session_number'), table_name='adler_risk_scores')
    op.drop_index(op.f('ix_adler_risk_scores_session_id'), table_name='adler_risk_scores')
    op.drop_index(op.f('ix_adler_risk_scores_risk_type'), table_name='adler_risk_scores')
    op.drop_index(op.f('ix_adler_risk_scores_patient_id'), table_name='adler_risk_scores')
    op.drop_index(op.f('ix_adler_risk_scores_id'), table_name='adler_risk_scores')
    op.drop_table('adler_risk_scores')
    op.drop_index(op.f('ix_adler_pharmacogenetics_results_tenant_id'), table_name='adler_pharmacogenetics_results')
    op.drop_index(op.f('ix_adler_pharmacogenetics_results_patient_id'), table_name='adler_pharmacogenetics_results')
    op.drop_index(op.f('ix_adler_pharmacogenetics_results_id'), table_name='adler_pharmacogenetics_results')
    op.drop_index(op.f('ix_adler_pharmacogenetics_results_gene'), table_name='adler_pharmacogenetics_results')
    op.drop_table('adler_pharmacogenetics_results')
    op.drop_index(op.f('ix_adler_patients_tenant_id'), table_name='adler_patients')
    op.drop_index(op.f('ix_adler_patients_status'), table_name='adler_patients')
    op.drop_index(op.f('ix_adler_patients_pk'), table_name='adler_patients')
    op.drop_index(op.f('ix_adler_patients_name'), table_name='adler_patients')
    op.drop_index(op.f('ix_adler_patients_id'), table_name='adler_patients')
    op.drop_table('adler_patients')
    op.drop_index(op.f('ix_adler_generated_documents_tenant_id'), table_name='adler_generated_documents')
    op.drop_index(op.f('ix_adler_generated_documents_session_id'), table_name='adler_generated_documents')
    op.drop_index(op.f('ix_adler_generated_documents_patient_id'), table_name='adler_generated_documents')
    op.drop_index(op.f('ix_adler_generated_documents_id'), table_name='adler_generated_documents')
    op.drop_index(op.f('ix_adler_generated_documents_document_type'), table_name='adler_generated_documents')
    op.drop_table('adler_generated_documents')
    op.drop_index(op.f('ix_adler_evolution_snapshots_tenant_id'), table_name='adler_evolution_snapshots')
    op.drop_index(op.f('ix_adler_evolution_snapshots_patient_id'), table_name='adler_evolution_snapshots')
    op.drop_index(op.f('ix_adler_evolution_snapshots_id'), table_name='adler_evolution_snapshots')
    op.drop_table('adler_evolution_snapshots')
    op.drop_index(op.f('ix_adler_engagement_flags_tenant_id'), table_name='adler_engagement_flags')
    op.drop_index(op.f('ix_adler_engagement_flags_severity'), table_name='adler_engagement_flags')
    op.drop_index(op.f('ix_adler_engagement_flags_patient_id'), table_name='adler_engagement_flags')
    op.drop_index(op.f('ix_adler_engagement_flags_id'), table_name='adler_engagement_flags')
    op.drop_index(op.f('ix_adler_engagement_flags_flag_type'), table_name='adler_engagement_flags')
    op.drop_table('adler_engagement_flags')
    op.drop_index(op.f('ix_adler_clinical_sessions_tenant_id'), table_name='adler_clinical_sessions')
    op.drop_index(op.f('ix_adler_clinical_sessions_session_number'), table_name='adler_clinical_sessions')
    op.drop_index(op.f('ix_adler_clinical_sessions_patient_id'), table_name='adler_clinical_sessions')
    op.drop_index(op.f('ix_adler_clinical_sessions_id'), table_name='adler_clinical_sessions')
    op.drop_index(op.f('ix_adler_clinical_sessions_approach'), table_name='adler_clinical_sessions')
    op.drop_table('adler_clinical_sessions')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_tenant_id'), table_name='adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_session_number'), table_name='adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_session_id'), table_name='adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_patient_id'), table_name='adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_id'), table_name='adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_clinical_analysis_json_approach'), table_name='adler_clinical_analysis_json')
    op.drop_table('adler_clinical_analysis_json')
    op.drop_index(op.f('ix_adler_appointments_tenant_id'), table_name='adler_appointments')
    op.drop_index(op.f('ix_adler_appointments_status'), table_name='adler_appointments')
    op.drop_index(op.f('ix_adler_appointments_pk'), table_name='adler_appointments')
    op.drop_index(op.f('ix_adler_appointments_patient_id'), table_name='adler_appointments')
    op.drop_index(op.f('ix_adler_appointments_id'), table_name='adler_appointments')
    op.drop_table('adler_appointments')
    op.drop_index(op.f('ix_adler_appointment_confirmations_tenant_id'), table_name='adler_appointment_confirmations')
    op.drop_index(op.f('ix_adler_appointment_confirmations_status'), table_name='adler_appointment_confirmations')
    op.drop_index(op.f('ix_adler_appointment_confirmations_source_message_id'), table_name='adler_appointment_confirmations')
    op.drop_index(op.f('ix_adler_appointment_confirmations_patient_id'), table_name='adler_appointment_confirmations')
    op.drop_index(op.f('ix_adler_appointment_confirmations_id'), table_name='adler_appointment_confirmations')
    op.drop_index(op.f('ix_adler_appointment_confirmations_appointment_id'), table_name='adler_appointment_confirmations')
    op.drop_table('adler_appointment_confirmations')
    # ### end Alembic commands ###
