"""Add maturity level to science tables

Revision ID: 293d5ebbd102
Revises: f14640a7c1a0
Create Date: 2026-06-04 12:01:23.105391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293d5ebbd102'
down_revision: Union[str, None] = 'f14640a7c1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_knowledge_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('target_table', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('clinician_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_knowledge_staging_id'), 'adler_knowledge_staging', ['id'], unique=False)
    op.add_column('adler_clinical_evidence', sa.Column('maturity_level', sa.Integer(), nullable=True))
    op.add_column('adler_medication_refs', sa.Column('maturity_level', sa.Integer(), nullable=True))
    op.add_column('adler_static_science', sa.Column('maturity_level', sa.Integer(), nullable=True))
    op.add_column('adler_therapeutic_protocols', sa.Column('maturity_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adler_therapeutic_protocols', 'maturity_level')
    op.drop_column('adler_static_science', 'maturity_level')
    op.drop_column('adler_medication_refs', 'maturity_level')
    op.drop_column('adler_clinical_evidence', 'maturity_level')
    op.drop_index(op.f('ix_adler_knowledge_staging_id'), table_name='adler_knowledge_staging')
    op.drop_table('adler_knowledge_staging')
    # ### end Alembic commands ###
