"""Add clinician profile and behavior models

Revision ID: 971244619ec7
Revises: 293d5ebbd102
Create Date: 2026-06-04 12:32:43.715875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971244619ec7'
down_revision: Union[str, None] = '293d5ebbd102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_clinician_behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_clinician_behavior_logs_id'), 'adler_clinician_behavior_logs', ['id'], unique=False)
    op.create_index(op.f('ix_adler_clinician_behavior_logs_session_id'), 'adler_clinician_behavior_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_adler_clinician_behavior_logs_user_id'), 'adler_clinician_behavior_logs', ['user_id'], unique=False)
    op.create_table('adler_clinician_preference_models',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('summary_profile', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('adler_clinician_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('primary_approach', sa.String(length=80), nullable=True),
    sa.Column('writing_style', sa.String(length=80), nullable=True),
    sa.Column('preferred_structure', sa.String(length=80), nullable=True),
    sa.Column('focus_bias', sa.String(length=80), nullable=True),
    sa.Column('document_style', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_clinician_profiles_id'), 'adler_clinician_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_adler_clinician_profiles_user_id'), 'adler_clinician_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adler_clinician_profiles_user_id'), table_name='adler_clinician_profiles')
    op.drop_index(op.f('ix_adler_clinician_profiles_id'), table_name='adler_clinician_profiles')
    op.drop_table('adler_clinician_profiles')
    op.drop_table('adler_clinician_preference_models')
    op.drop_index(op.f('ix_adler_clinician_behavior_logs_user_id'), table_name='adler_clinician_behavior_logs')
    op.drop_index(op.f('ix_adler_clinician_behavior_logs_session_id'), table_name='adler_clinician_behavior_logs')
    op.drop_index(op.f('ix_adler_clinician_behavior_logs_id'), table_name='adler_clinician_behavior_logs')
    op.drop_table('adler_clinician_behavior_logs')
    # ### end Alembic commands ###
