"""Add official document templates

Revision ID: b5be607d15f0
Revises: 971244619ec7
Create Date: 2026-06-04 12:52:31.062899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5be607d15f0'
down_revision: Union[str, None] = '971244619ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_document_templates',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('official_source', sa.String(length=180), nullable=True),
    sa.Column('content_structure', sa.JSON(), nullable=True),
    sa.Column('maturity_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_document_templates_document_type'), 'adler_document_templates', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adler_document_templates_document_type'), table_name='adler_document_templates')
    op.drop_table('adler_document_templates')
    # ### end Alembic commands ###
