"""Add session note drafts table

Revision ID: dcfb1efc9112
Revises: 0165039044d4
Create Date: 2026-06-05 20:57:29.895549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfb1efc9112'
down_revision: Union[str, None] = '0165039044d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_session_note_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_session_note_drafts_id'), 'adler_session_note_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_adler_session_note_drafts_patient_id'), 'adler_session_note_drafts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adler_session_note_drafts_tenant_id'), 'adler_session_note_drafts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adler_session_note_drafts_tenant_id'), table_name='adler_session_note_drafts')
    op.drop_index(op.f('ix_adler_session_note_drafts_patient_id'), table_name='adler_session_note_drafts')
    op.drop_index(op.f('ix_adler_session_note_drafts_id'), table_name='adler_session_note_drafts')
    op.drop_table('adler_session_note_drafts')
    # ### end Alembic commands ###
