"""Add scientific knowledge models

Revision ID: f14640a7c1a0
Revises: 05e2adf69ea6
Create Date: 2026-06-04 11:50:19.185648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14640a7c1a0'
down_revision: Union[str, None] = '05e2adf69ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adler_clinical_evidence',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=180), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('evidence_level', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_clinical_evidence_source'), 'adler_clinical_evidence', ['source'], unique=False)
    op.create_index(op.f('ix_adler_clinical_evidence_subject'), 'adler_clinical_evidence', ['subject'], unique=False)
    op.create_table('adler_medication_refs',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('generic_name', sa.String(length=180), nullable=True),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('interactions_json', sa.JSON(), nullable=True),
    sa.Column('monitoring_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_medication_refs_generic_name'), 'adler_medication_refs', ['generic_name'], unique=False)
    op.create_table('adler_static_science',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_static_science_category'), 'adler_static_science', ['category'], unique=False)
    op.create_index(op.f('ix_adler_static_science_source'), 'adler_static_science', ['source'], unique=False)
    op.create_index(op.f('ix_adler_static_science_subject'), 'adler_static_science', ['subject'], unique=False)
    op.create_table('adler_therapeutic_protocols',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('approach', sa.String(length=80), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('indications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adler_therapeutic_protocols_approach'), 'adler_therapeutic_protocols', ['approach'], unique=False)
    op.create_index(op.f('ix_adler_therapeutic_protocols_name'), 'adler_therapeutic_protocols', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adler_therapeutic_protocols_name'), table_name='adler_therapeutic_protocols')
    op.drop_index(op.f('ix_adler_therapeutic_protocols_approach'), table_name='adler_therapeutic_protocols')
    op.drop_table('adler_therapeutic_protocols')
    op.drop_index(op.f('ix_adler_static_science_subject'), table_name='adler_static_science')
    op.drop_index(op.f('ix_adler_static_science_source'), table_name='adler_static_science')
    op.drop_index(op.f('ix_adler_static_science_category'), table_name='adler_static_science')
    op.drop_table('adler_static_science')
    op.drop_index(op.f('ix_adler_medication_refs_generic_name'), table_name='adler_medication_refs')
    op.drop_table('adler_medication_refs')
    op.drop_index(op.f('ix_adler_clinical_evidence_subject'), table_name='adler_clinical_evidence')
    op.drop_index(op.f('ix_adler_clinical_evidence_source'), table_name='adler_clinical_evidence')
    op.drop_table('adler_clinical_evidence')
    # ### end Alembic commands ###
